# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/redlance/Geekbrains/Python  prepare/Repository/Python-dev-Interview-prep/Lesson_7/design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 523)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.get_db_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_db_button.sizePolicy().hasHeightForWidth())
        self.get_db_button.setSizePolicy(sizePolicy)
        self.get_db_button.setMinimumSize(QtCore.QSize(25, 10))
        self.get_db_button.setObjectName("get_db_button")
        self.verticalLayout.addWidget(self.get_db_button)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout_3.addWidget(self.delButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 546, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuTable = QtWidgets.QMenu(self.menuBar)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menuBar)
        self.actionCategories = QtWidgets.QAction(MainWindow)
        self.actionCategories.setEnabled(False)
        self.actionCategories.setObjectName("actionCategories")
        self.actionEmployees = QtWidgets.QAction(MainWindow)
        self.actionEmployees.setEnabled(False)
        self.actionEmployees.setObjectName("actionEmployees")
        self.actionGoods = QtWidgets.QAction(MainWindow)
        self.actionGoods.setEnabled(False)
        self.actionGoods.setObjectName("actionGoods")
        self.actionPositions = QtWidgets.QAction(MainWindow)
        self.actionPositions.setEnabled(False)
        self.actionPositions.setObjectName("actionPositions")
        self.actionUnits = QtWidgets.QAction(MainWindow)
        self.actionUnits.setEnabled(False)
        self.actionUnits.setObjectName("actionUnits")
        self.actionVendors = QtWidgets.QAction(MainWindow)
        self.actionVendors.setEnabled(False)
        self.actionVendors.setObjectName("actionVendors")
        self.menuTable.addAction(self.actionCategories)
        self.menuTable.addAction(self.actionEmployees)
        self.menuTable.addAction(self.actionGoods)
        self.menuTable.addAction(self.actionPositions)
        self.menuTable.addAction(self.actionUnits)
        self.menuTable.addAction(self.actionVendors)
        self.menuBar.addAction(self.menuTable.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Путь к базе данных:"))
        self.label_2.setText(_translate("MainWindow", "(пусто)"))
        self.get_db_button.setText(_translate("MainWindow", "Выбор БД"))
        self.addButton.setText(_translate("MainWindow", "Добавить запись"))
        self.delButton.setText(_translate("MainWindow", "Удалить запись"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.actionCategories.setText(_translate("MainWindow", "Categories"))
        self.actionEmployees.setText(_translate("MainWindow", "Employees"))
        self.actionGoods.setText(_translate("MainWindow", "Goods"))
        self.actionPositions.setText(_translate("MainWindow", "Positions"))
        self.actionUnits.setText(_translate("MainWindow", "Units"))
        self.actionVendors.setText(_translate("MainWindow", "Vendors"))
